<a href="https://colab.research.google.com/github/radhakrishna1435/ML_23AG1A66E4/blob/main/Welcome_To_Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

In [6]:
array1=np.array([1,2])
print(array1)

[1 2]


In [7]:
arr2= np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [9]:
arr3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(arr3)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [13]:
Data = np.array([10, 15, 20, 25, 30, 35, 40])
mean = np.mean(Data)
print(f"Mean is {mean}")
median = np.median(data)
print(f"Median is {median}")

Mean is 25.0
Median is 25.0
